"""Create Intial Migration

Revision ID: 0001
Revises:
Create Date: 2026-06-24 16:29:07.281334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("short_code", sa.String(length=50), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="my_url_shortener",
    )
    op.create_index(
        "idx_short_code", "urls", ["short_code"], unique=True, schema="my_url_shortener"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_short_code", table_name="urls", schema="my_url_shortener")
    op.drop_table("urls", schema="my_url_shortener")
    # ### end Alembic commands ###
